version: "3.3"

services:
  postgres:
    image: postgres:11
    container_name: ${POSTGRES_NAME}
    hostname: ${POSTGRES_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_EXPOSE_PORT}:${POSTGRES_PORT}'
    volumes:
      - '${POSTGRES_DATA_DIR}:/var/lib/postgresql/data'
    restart: always

volumes:
  postgres-data:
