version: "3.3"
services:
  mongo:
    image: mongo:4.2
    container_name: ${MONGO_NAME}
    hostname: ${MONGO_NAME}
    environment:
      - MONGO_DATA_DIR=${MONGO_DATA_DIR}
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - ${MONGO_DATA_DIR}:/data/db
    ports:
      - '${MONGO_EXPOSE_PORT}:${MONGO_PORT}'
    restart: always
  backend:
    build:
      context: '.'
      dockerfile: Dockerfile
    container_name: ${BACKEND_NAME}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    environment:
      - NODE_ENV=${BACKEND_ENV}
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=UTC
      - TZ=UTC
    ports:
      - '${BACKEND_EXPOSE_PORT}:${BACKEND_PORT}'
    depends_on:
      - 'mongo'
    links:
      - 'mongo'
volumes:
  mongodb:
